### ISSUE TITLE
FormNotFoundError: no form matching nr 0

### ISSUE THREAD

**Issue by n0p** [bmenendez/20up#14]
```
| Traceback (most recent call last):
|   File "./20up.py", line 228, in <module>
|     main()
|   File "./20up.py", line 180, in main
|     wrap = Wrapper(email, password, True)
|   File "/srv/owncloud/n0p/files/t20/bmenendez-20up-e2afb40/tntwrapper.py", line 49, in __init__
|     if not self.tnt.doLogin(email, password):
|   File "/srv/owncloud/n0p/files/t20/bmenendez-20up-e2afb40/tntapi.py", line 76, in doLogin
|     self.br.select_form(nr = 0)
|   File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 524, in select_form
|     raise FormNotFoundError("no form matching "+description)
| FormNotFoundError: no form matching nr 0
```

Cuando estaba haciendo un full backup ha ocurrido esto.
Ahora salta este mismo error cada vez que intento hacer login

**Comment by mig42** [comment]
+1

**Comment by pando85** [comment]
+1

**Comment by VictorSeven** [comment]
No se me llega a ejecutar el programa por lo mismo:

```
| Traceback (most recent call last):
|   File "<string>", line 228, in <module>
|   File "<string>", line 180, in main
|   File "C:\Users\kibon\Desktop\20up\tntwrapper.py", line 49, in __init__
|   File "C:\Users\kibon\Desktop\20up\tntapi.py", line 76, in doLogin
|   File "C:\Python27\lib\site-packages\mechanize-0.2.5-py2.7.egg\mechanize\_mec
hanize.py", line 524, in select_form
| FormNotFoundError: no form matching nr 0
|
------------------------------------------------------------
|
| Ha ocurrido un error inesperado: no form matching nr 0
```

**Comment by pando85** [comment]
death tuenti?

**Comment by penyaskito** [comment]
Esta es la respuesta que llega, y por lo que no se encuentra el formulario:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" /><meta name="google" content="notranslate" /><title>Tuenti</title><link rel="shortcut icon" href="https://estaticos2.tuenti.com/layout/cupcake/img/dot_t_favicon.IU0P2xfouE.png" /><script type="text/javascript"> document.domain = location.host.match(/tuenti\.com(?:$|:)/) ? 'tuenti.com' : 'tuenti.local'; var realURL=''; try { if ( window == window.top ) { realURL = window.top.location.href; } else { realURL = location.href; } }catch(ex){ }function redirectToLogin(realURL) { if(realURL == '') { self.location.href='https://www.tuenti.com/?m=Login'; } else { withoutPound = realURL.replace('/#', '/?'); if (withoutPound.indexOf('?') >0) { joiningChar = '&'; } else { joiningChar = '?'; } self.location.href = (withoutPound + joiningChar + 'gotHash=1'); } } redirectToLogin(realURL);</script><style type="text/css" media="screen">div { position:absolute; top:10px; left:10px; text-align:left; z-index:10000000; } h1 { font: bold 13px Arial,Helvetica,sans-serif; margin:0; padding:0; color:#333333; } h2 { font: normal 11px Arial,Helvetica,sans-serif; margin:0; padding:0; color:#999; margin-top: 5px; }  a { text-decoration:none; color:#2C61A3; }  a:hover { text-decoration:underline; }</style></head><body><div><h1>La sesión ha caducado. Te redirigiremos a la página de acceso...</h1><h2>Si no ves la página de acceso en 5 segundos, <a href="https://www.tuenti.com/?m=Login" title="Acceder">Pincha aquí</a></h2></div></body></html>
```

**Comment by pjanaya** [comment]
Igual por aquí.

PD.: Todos corriendo a rescatar nuestras vergonzosas fotos de antaño, ¿eh? xDDD

**Comment by pando85** [comment]
Hace 10 min no las queriamos y ahora no podemos vivir sin ellas.

**Comment by penyaskito** [comment]
Parece que m.tuenti.com lo han desactivado xD

**Comment by bmenendez** [comment]
Hola a todos,

Efectivamente, ahora no encuentra el formulario para hacer login. Tuenti se ha debido dar cuenta de la información que ha salido a la luz y han desactivado la versión móvil, que era la que parseaba.

Un saludo y muchas gracias por vuestro interés :-)

Borja.

**Comment by joseajp** [comment]
Vaya por dios, aquí venía yo también a poner la issue.
Mucha suerte, Borja :)

**Comment by aantoniic** [comment]
Buenas tardes Borja.

Entonces, ¿se solucionará o la aplicación pasará a mejor vida?

Saludos!! Y grandioso trabajo, de momento me ha dado para descargar un cuarto de biblioteca.

**Comment by Inlacou** [comment]
+1

**Comment by RubenEsposito** [comment]
+1

**Comment by gsusI** [comment]
+1

**Comment by pepperoney** [comment]
+1

**Comment by taniarv** [comment]
Ídem, ¿se va a poder solucionar?

**Comment by mig42** [comment]
Hay que admirar este grandioso F*CK YOU por parte del equipo Tuenti.

**Comment by jajube** [comment]
@bmenendez Que pena, tanto trabajo para esto, ya podían haber dejado online la versión móvil.

**Comment by ShinSgo** [comment]
ups, venia a postear lo mismo....

**Comment by txomon** [comment]
Tras un buen rato mirando a fondo, parece que han hecho un redirect forzado para las versiones móviles, no dejando ver cosas de la red social desde el endpoint movil.

**Comment by sergiomcalzada** [comment]
Si puedes parsear la web "normal" y sacar los ids de las fotos de los álbumes puedes obtener la url de descarga de la fotos de "https://www-1.tuenti.com/index.cupcake.php?m=Photo&func=getAdditionalActions&itemKey={ID_DE_LA_FOTO}"

Supongo que tendrás que gestionar cookies y demás (cosas que para la versión actual ya se debe estar haciendo).

Un  saludo, y suerte ;)

**Comment by alejandrofcarrera** [comment]
https://www.tuenti.com/movil/login esta web está habilitada, pero efectivamente se obliga la redirección desde el subdominio m.*

**Comment by txomon** [comment]
Buenas!

Ayer por la noche hice un sprint de 4 horas y al ir a comprobar finalmente que mi script functionaba, lo borré xD. Peeero lo volví a escribir y funciona. El problema es que he tenido que implementarlo a lo bruto.

El script lo que hace básicamente es descargarse todas las fotos de tu perfil, las que has subido tu, consigue todos los userId que haya en esas fotos, y luego hace lo mismo con esos.

Siento mucho decir que no puedo distribuir esto, porque en mi caso, teniendo 1000 fotos, ha descargado 30k de fotos... muchas de mis contactos y tal... por ello, he tuiteado a los de @tuenti y me han respondido que van a sacar una herramienta.

Voy a seguir jugando para ver si consigo filtrar solo en las que aparece uno y lo compartiré entonces...

**Comment by txomon** [comment]
Vale, he jugado suficiente como para que converja la descarga, pero no tiene ni por asomo el nivel de compatibilidad de esta app. Es un script para hacer backup de mis fotos. Si tenéis instalada la librería libgexiv2 te mete el timestamp en la foto, para que sepas cuando fue añadida (menos da una piedra).

https://github.com/txomon/tuenti-downloader

**Comment by pando85** [comment]
Buen trabajo @txomon.

**Comment by txomon** [comment]
La clave está en que si no mandas userid en el GetAlbumPhotos, te devuelve para el usuario actual. El problema es que no he encontrado una manera de saber quienes son tus amigos... Si alguno pudiera mejorar el algoritmo de scrapping sería genial!

Voy a intentar ampliar el script esta noche para meterle persistencia  y así poder ir haciendo pruebas de algoritmos sin sobrecargar los servidores.

**Comment by n0p** [comment]
Yo creo que si @bmenendez no va a trabajar más en este script podemos cerrar el issue y dejar de spamearlo xD

**Comment by alejandrofcarrera** [comment]
@txomon para conseguir los amigos, puedes bajarte el json directamente desde la página de Tuenti... Parece que has tirado por la librería de Python en vez de scrappear la web como era anteriormente.

**Comment by txomon** [comment]
@alejandrofcarrera si, scrappear la web requería analizar todo el tráfico que estaba enviando y no tenía ganas de implementarlo (quería que fuera un proyecto de 4 horas xD).

O sea que tiré por una librería que estuviera ya hecha.

Pero si alguien quiere documentar o/y generar una librería que scrapee correctamente, seguramente podamos cambiar la implementación. Por el momento me parecía lo más asequible, ya que la web lleva un cojón de JS.

**Comment by jomaceld** [comment]
Hola @txomon ,

Con `User_getUsersData({'ids': [user_id]})` puedes obtener información sobre un usuario. hay un campo `relationship` que esta a 0 si el usuario no es amigo.

Por lo que he podido comprobar, con la API que utilizas el problema es que te devuelve las imagenes que ha subido ese usuario pero no en las que esta etiquetado. Estaría bien para poder recuperar las que te han añadido, si te enteras de como avísame.

**Comment by txomon** [comment]
Efectivamente falta saber las imágenes en las que está uno etiquetado. Mi
idea era hacer scrapping a lo bruto, tirando de todos los usuarios que se
pueda y comprobar si sois amigos, y si lo sois comprobar sus fotos para ver
en cuales estas etiquetado.

Por el momento había pensado en meter persistencia en el programa para
poder hacer las pruebas más rápido. En el TODO tengo tareas a corto plazo
por si te animas a implementar alguna.

Meteré testing esta noche si tengo tiempo para los PR

**Comment by txomon** [comment]
Estoy muerto de sueño y no voy a programar nada hoy, pero si queréis, he abierto un chat en [![Gitter](https://badges.gitter.im/txomon/tuenti-downloader.svg)](https://gitter.im/txomon/tuenti-downloader?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge), dejad los comentarios allí o mandar PRs y los miro mañana

**Comment by bmenendez** [comment]
Hola a todos,

Me alegra ver tanto movimiento :D os agradezco el esfuerzo que estáis haciendo, siento no haberme podido pasar por aquí a comentar.

Gracias a la idea de @alejandrofcarrera, he usado Selenium para que renderice el javascript y se encargue de la sesión de usuario. Por el momento solo puede descargar fotos y sus comentarios, pero no los comentarios de tablón (me falta saber a qué función de javascript tengo que llamar para cargar más comentarios) ni los datos de los contactos. No he tenido tiempo de más. Si queréis, echadle un ojo y me decís.

Cierro ya este issue y abro uno nuevo para los comentarios de tablón y otro para los datos de los contactos ;-)

Un saludo,

Borja.

PD: muy buena idea lo del gitter!!
