### ISSUE TITLE
Obtener comentarios de tablón

### ISSUE THREAD

**Issue by bmenendez** [bmenendez/20up#15]
Se hace necesario salvar también los comentarios de tablón. Aquí el problema reside en saber cómo hacer para seguir cargando más hasta que se llegue al final.

**Comment by alejandrofcarrera** [comment]
Te hago pull request esta noche pues lo tengo implementado.

**Comment by alejandrofcarrera** [comment]
Tienes un PR. Cambia lo que creas conveniente. Ha sido testeado.
