### ISSUE TITLE
Obtener datos de contactos

### ISSUE THREAD

**Issue by bmenendez** [bmenendez/20up#16]
Falta la información de los contactos. Todavía no he pensado ni cómo, pero imagino que se podrán obtener los contactos por lo del chat de la derecha y, a partir de ahí, algo de su información.

**Comment by alejandrofcarrera** [comment]
Si consigues el csrf token que está utilizando en la web (home u otra) tienes forma de conseguir esta información con una llamada (todos tus contactos): id, photo, name, first name y last name.

**Comment by alejandrofcarrera** [comment]
Tienes un PR. Cambia lo que creas conveniente. Ha sido testeado.

**Comment by bmenendez** [comment]
Creo que ahora no tiene mucho sentido descargar la información de los contactos, ya que no se puede obtener ni el cumpleaños ni el número de teléfono.

En cualquier caso, gracias por tus aportes :-)
