### ISSUE TITLE
Error ejecutar script Linux Manjaro

### ISSUE THREAD

**Issue by sdsoldi** [bmenendez/20up#2]
Cuando intento ejecutar el script salta este error.

[joseba@joseba-manjaro 20up-master]$ python 20up.py
  File "20up.py", line 45
    print '-' * 60
            ^
SyntaxError: invalid syntax

Estoy usando Python versión 3.3.5 y debe ser un problema de esta versión.
Los Print ahora van con parentesis. 
print ('-' * 60)

Probado. Con esto no salta error.

**Comment by hecoding** [comment]
Me pasaba exactamente lo mismo. Lo he "portado" a 3, hablo de ello en un issue.

**Comment by bmenendez** [comment]
De momento, 20up va a seguir estando escrito en Python 2.7, por lo que cierro el issue.
