### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1,855'

### ISSUE THREAD

**Issue by jhbecares** [bmenendez/20up#20]
Al intentar descargar las fotos me da el siguiente error:
ValueError: invalid literal for int() with base 10: '1,855' 
y no se pueden descargar.
¿Dónde?
OS X Yosemite 10.10.5
Python 2.7.9 :: Anaconda 2.2.0 (x86_64)
Browser: Firefox

Como chapuza rápida he comentado esta línea
`#number = int(string(finalNumber))`
en la función getAllAlbums (que es donde daba el error) y le he pasado directamente el número 
`nnl = [name, 1855, TWENTY_HOST + link]`

¿Alguna idea de cómo convertir el unicode para que no pase esto?

**Comment by alejandrofcarrera** [comment]
La única aparición de esa variable en el método getAllAlbums es bien diferente a la que comentas.

Creo que tienes una versión antigua del repositorio. Mi recomendación es que realices el clone o descarga nuevamente y compruebes que está como tú sugieres.

Un saludo.

**Comment by jhbecares** [comment]
Perdón, me refería a:  
`number = int(finalNumber)`
Lo que había puesto arriba era mi intento de arreglarlo. Desastre...
Me he bajado el exe más reciente y he probado en windows y me da el mismo error. No sé qué puede estar pasando... De todos modos muchas gracias.

Saludos.

**Comment by alejandrofcarrera** [comment]
Vale. En el fichero tntapi.py, línea 110 - 114 se hace el tratamiento del número.
Yo he reemplazado esas líneas por esto en mi copia local:

```number = int(withoutSpace[-1][1:-1].replace('.', ''))```

Un saludo.

**Comment by bmenendez** [comment]
Problema solucionado en la última actualización :-)

Dependiendo del sistema, los números de cuatro o más cifras se escriben con coma o con punto.
