### ISSUE TITLE
Imposible abrir con Chrome en Debian

### ISSUE THREAD

**Issue by JuanjoSalvador** [bmenendez/20up#24]
En Debian (Linux) no soporta Google Chrome aunque este sea el navegador predeterminado. La solución es elegir Firefox (aunque tengas Iceweasel).

Posiblemente sea un problema de Chrome en lugar de 20up, pero conviene reportar el error.

**Comment by bmenendez** [comment]
Hola @JuanjoSalvador,

Imagino que sí, pero, ¿te has descargado [ChromeDriver](http://chromedriver.storage.googleapis.com/index.html?path=2.21/) para tu versión de Linux?

Un saludo,

Borja

**Comment by JuanjoSalvador** [comment]
Pues no, siempre he usado Chromium, hace poco me pasé a Chrome. De todos modos, desde Iceweasel va sin problemas.

**Comment by bmenendez** [comment]
ChromeDriver no es un navegador web, es el [WebDriver](https://www.w3.org/TR/webdriver/) para poder comunicarte con Chrome :-) En las propias [instrucciones de 20up](http://bmenendez.github.io/20up/#necesitas-instrucciones) viene especificado que lo necesita.

Gracias igualmente! :-)
