### ISSUE TITLE
Error inesperado al cambiar de álbum

### ISSUE THREAD

**Issue by JuanjoSalvador** [bmenendez/20up#25]
En Debian (Linux) con Python 2.7.11

`Traceback (most recent call last):
|   File "20up.py", line 229, in <module>
|     main()
|   File "20up.py", line 187, in main
|     ret = wrap.downloadAllPictures(False)
|   File "/home/juanjo/bmenendez-20up-5d215e0/tntwrapper.py", line 171, in downloadAllPictures
|     self.downloadPicturesFromAlbum(album, totalPictures, alreadyDownloaded, comments)
|   File "/home/juanjo/bmenendez-20up-5d215e0/tntwrapper.py", line 98, in downloadPicturesFromAlbum
|     pic = self.tnt.getPicture(comments)
|   File "/home/juanjo/bmenendez-20up-5d215e0/tntapi.py", line 162, in getPicture
|     element = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.ID, INFOS['idPhotoImage'])))
|   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
|     raise TimeoutException(message, screen, stacktrace)
| TimeoutException: Message: 
| 
|
------------------------------------------------------------
|
| Ha ocurrido un error inesperado: Message: `

**Comment by JuanjoSalvador** [comment]
La solución por el momento es lanzar de nuevo el scrapping. Se salta todos los álbumes que haya procesado y comienza por el que ha fallado.

**Comment by bmenendez** [comment]
Hola @JuanjoSalvador, 

Creo que ya está solucionado el problema, ¿podrías probarlo y contarme si es así? :-)
