### ISSUE TITLE
Ya no es posible usar 20up??

### ISSUE THREAD

**Issue by baldman89** [bmenendez/20up#29]
![error 20up](https://cloud.githubusercontent.com/assets/17629851/13515322/9b9afcd0-e1b0-11e5-9445-e608cf98f14b.jpg)

Buenas noches, acabo de leer que ya es posible descargar las fotos desde la app de Tuenti, y que también se puede hacer desde tu herramienta, la verdad es que antes de concederle mi numero de teléfono a Tuenti para que lo mercantilice, prefería usar 20up, pero desgraciadamente he probado a través de Chrome (con la extensión en la misma carpeta que 20up.exe) y con Firefox actualizados a la última versión, y en ambos casos salta el mismo error (te lo adjunto en una imagen) He probado solo a descargar las fotos y también el resto de opciones...

Desconozco si la calidad de las fotos que te envía Tuenti son la misma que la que se descarga con tu herramienta (te envía las fotos por mail-¿entrarán como adjunto con una calidad decente?), pero es que además tu ofreces también descargar los comentarios y el tablón...además no se si la app de Tuenti también te da las fotos etiquetadas y subidas por otros que ya no son tus amigos...

¿Crees que podrás ponerle solución de nuevo o dejarás el proyecto en stand-by?

Te agradezco de antemano tu generosidad y tu esfuerzo, un saludo.

**Comment by bmenendez** [comment]
Hola @baldman89,

Entiendo tu preocupación por lo del número de teléfono. El problema que existe ahora es que, si te metes a la red social, ya no puedes navegar por las fotos ni ver tu tablón. Por ello, 20up ha quedado completamente inútil. Poca solución le veo ya a esto, sinceramente.

En cualquier caso, he probado con la app que te ofrecen ellos ahora y lo que hacen es mandarte un e-mail con un enlace para que te descargues las fotos. Es un .zip que contiene todas tus fotos con sus respectivos comentarios, todo en formato HTML :-)

Siento no poder ser de más ayuda.

Un saludo,

Borja.
