### ISSUE TITLE
Fallo en encoding de caracteres en backupUsers()

### ISSUE THREAD

**Issue by ellocoyo** [bmenendez/20up#3]
Al iterar sobre ciertos usuarios, lanza:
```python
 'charmap' codec can't encode character u'\xc1' in position 22: character maps to <undefined>
```

Mira a ver si sirve: http://stackoverflow.com/questions/15739029/python-unicodeencodeerror-when-i-use-grep

**Comment by bmenendez** [comment]
Ya no existe un backupUsers, por tanto este error ya no existe :-)
