### ISSUE TITLE
La primera foto descargada de cada álbum es una miniatura

### ISSUE THREAD

**Issue by guillermogf** [bmenendez/20up#4]
La primera foto de cada álbum, es decir, la última añadida en orden cronológico se descarga como miniatura pese a que esté disponible en mayor resolución.

**Comment by bmenendez** [comment]
Problema solucionado en #0512537 :-)

**Comment by bmenendez** [comment]
Problema solucionado en bmenendez/20up@05125376d824caef0bcaf0b27e0588a7c8a092cf
